global:
  istio:
    ingressGateway:
      namespace: istio-ingress

subDomain: ververica

encryptedLicense: BABtep0Jzb6qhAg5NKllK1fysjA/60yC7fCJD8xY9hAPMoaGSRyGvhMp/RNY05iGG27+zhFSyWPwe6huAAAmY6Bn6vOyA77u+HzM8Pd9g8nl7987uyqOM3L6n5+h8ou0q/A9ktvjXzYTl5E1Jn8JQUVJ6QfDpZPTUdfKfZkeFAN0HuhZ4Svy50/Xymm6KMgZQHi//N0xkmUIWwqY2p25lrz7Wy6kxlohCUJCd2yadk50vs6kZWVXOiBtWEoXr7WDm23UuAXEn+U/LfFTg0sXV0fpUpDjsVpq6pw33zomlelLgypm/KNHDwsJKrfMQOAwkLAwwmaCr7jbdpbW/m8Dvt9iZGrl9nOS9bwM6xEiYMqxCnYARCq3TfBLo8fGfdjo4nnXEVnCcecLOlIvsIp6uiXNLEJ0xc2UOEHYO5woJzmBFMMzD6WOelQy+mVdwncobaddsXydfT7hOtHJ7gZ5tgWQ5PqE5bJDWgPfzCWToSP7sZua7xiocfgA1jUo2jivSmOv+QHRQrlXFdk/f3zdAnXhPCicxk67jwJFZLKbtuR7CQGxG9xQvsw/nXi+1SpQqB0wpYdfcOT+gAuq4p+1SXcWw0Sl8XUeeRTwRvHFBIeiHHKIbzrEMygYQtT5LKuRosnCOSzVqDoTMB5M9yTnCpWxbpmIdYrMeuxwxYQ9TNJ6r1ZnsjikJpKrM66e/7HW4dJgjxGszw7ik3Uu2/qVioN7/vUoJaF8wmI8noaaoEd8zENK2B5VhgEZDXMWMIzcPqA9qJ1oDqv3P5TvlAmylPotLDh4M6S66aXp06HQfVA14LuOZDYukTs4emQsIXhrGQUQ2XRw81SRi9HTxX8cbcyds8R0jcMjyNMgZdp28GJ22wA1EmxRfpN0aaPcJTLeZpaxBpU479jr192GGrhCd17xhR3HT1VSNzmsbyOppiQ8SrxBgLzErhCQYuzPVA4DubE0bHKclEmNRNtYnbQ5FgnqD/RsH9HWN3Xx+sDgAA8wbOXh8fet7CTvLJhuDpZOM43uODG1vq56RG65Uy6wodr++gKWRgovFcdKWEy21OnIkrX3Phw67COVlwNLRk78zvBTX37KLi2aAnQRmlBS25esI6+0fxmdXVNdDU7ury+q1Qv4Sth3vqqBMkZ94YzAflQTGWx+RekyqJ9dGQ7h4qMQ4cOnZoo7NBEO0SLFv66dDqUWlxTlitqlurgAK7UH2NSnY5bgcbWieetWibQ1fUOycey20uzejj0CVSlmDzBQoMs/rerWurUjjejcp/BDR4rg2Qn2Fg4pxU8ObKXfdGPSuqq/pLYmumB4VPZag46mIel2F344TpLEQPAnefCKcaPbSl07XmstIWstxDk7DCwb9AkCiBkQQ1LCCbfTF/tvAXifsBxllACo/tFtpK0G5bbnXKgi2VU8OqElYsPifCpieema5rPFBDdX0Na5r0dTFM8A5G3xJTNirfzSu+JiGkQuDVCah3SMgUrB8nAxGscYTSBtKnlMmI7TBlcyJPxWsorC7h/DOhPVTkUEDkOFrUbuMuC6qdk+CSJOKiuCsp5Ks8SxKiceHeBHK7UR18nBBlbYtINIi2VRgwE0wnYqT+V1yGt5xQhssOo5KTftNmrn8OBuZh2lzcTjWfHUB6MeAModP1rQgOXPZuTtsjklN5SCbnPlpXrpXOSL+bOafK78pKQgue72kUgVWifCvn1JcK2J2+x3rKSsa0tSKg+ZHKatFTSmvPcvRUrZf7Rd9oNbL6wEnV846P5Oysu9tc59YIxLJcc9+9wgZ0oyfaYXITxfDVjBJcMUvdkHTnoWHqX71vCr0PKh0j3EmVkCcRZfilbBhWRygBtl588Opu83tl01KniAHl9/hn7iYHJa44nXgfm08ONSf66dKBXwQuVMh111WR1wPp5xQYRsygTzohXrq1d92Ah051vCSl2DoCECxa7xuFZReZFFn3fXvdYJ8mrJv3G/DuZoZY0Zr4S4Ra1w09nTcDhLln+hnOB3eo89UseA6LNmhiMChvoq9xS0YOxuc7/MuEFnT+0bfP5wy/5G4Hw5mwO8r8BcwV32sWSqHLdgfTUh+m3AuD+xA2MtyHk9z0fRXDMtmemxaM6oTqMQ+pLnEvQwmco1S4qZz2X5Bpw50hIaR+VCRJ9gzwAFLCKKs0Mhi8dh1YI5p9WwxB1HqKyo+wKs3t3KtELAvGKPtwT1QH9JCr2ANukIWcfCe6NyxpdWLvLsYXtOeFt7l6H460HWdLTk968xoVWH3sc8ZJgA+YUETLyG2eSvKoCRt3Y74v7GDiDn4S93jGHJDTiXGR2vuq5wXFcwU6Z+kWiTDKX9oi7sF7xBNObAwD/FzwVv145uO7po3m5QDWAu98qfZbEcasRcrFVLAK6XulZeNDa5WMI1+fhmxvibeD5L7GNrufBhyB2AtjMkoUdRnR5No5bKkiAHZA/H1zXmB93oWotGymmClMAhyYfXHWVcm+6A7NViyrpeaeWDX/Btwj+pxKXScjDfPtZsB60Vsl2Sz+uAkLfFUSmSoXdkiKTNuW+JbzOOv6vki8gnHo4TEch2FCtvPgPhJQh9nHl3ODRUNMmYAp3iXLv73UQWKzB6i21/RKFjniHGXN+9CsYC5/VhbHrGsAWwvvosU+9UBGrBaDuQ9iVMPQUFyV4oXOKz8fK/3x1Tj46321ROpqDRRPNkYNQvcNfm2nwAKJvySQp4D4BaGDoOCCIEC/kyXCV/5TrQfuowazgp32kmDPF/QaQx20SUiHBVQONDWEwQWPK0WpKElVwYFVYSnLfsEGHIhianLPNAGF/DjRLdIKFAnrPunA06VOiLggOkv5Krgi/qHv2i/0qzqZI3Aio5IjjRqkvSTC56SQ12DcyfNgH7j/4UhLsWjMclouq4DalF0lfGS9qOgRtF72mahAcNHD+NuBJ+x8lLQoObk+YHKq3Qyrl/Grv+5WGB4WceNda7Ixe8YYCTdTz3//ILd+EnUE7er01IdUL1XGSo/fimVlgYPRqGvtEcn5UU/KmUBXFN8Dov6rlrPbsi3ScmdadgmkccVlb9hZ7/7Eu1PGCyXNvC1KMDHs27iYcPI9O4GeVxa0n/Uu8dz0TBaz3JbGrbEGIBEQ1beN6RtQLAeUv80HaRV9wRigsXwcHp1ELv3KzG2yEYOYCoQiT5PZ+pyh5SFXgq/HUT972DfKiKvqzY6Qbq/pozVhC5f+mGMATkfy33xvOkjHCYGbbG+AanDDSwUrabXogU1hM9vRpOANkR/WGFIxolXnn8kmF8W6BOt2t6QTnFhstIQ4ckiSZ2ok0tT/p8iHhOp/dvFwBsN3qdA29zothyePdz

ververica-platform:
  vvp:
    ### Configure VVP to use a local SQLite database
    persistence:
      type: local

    ### Configure Minio for Universal Blob Storage
    blobStorage:
      baseUri: s3://steadops-playground-bucket
      s3:
        endpoint: http://minio.minio.svc.cluster.local:80

    ### Configure some global defaults for Deployments in this instance of Ververica Platform
    globalDeploymentDefaults: |
      spec:
        state: RUNNING
        template:
          spec:
            resources:
              jobmanager:
                cpu: 0.5
                memory: 1G
              taskmanager:
                cpu: 0.5
                memory: 1G
            flinkConfiguration:
              state.backend: filesystem
              taskmanager.memory.managed.fraction: 0.0 # no managed memory needed for filesystem statebackend
              high-availability: kubernetes
              metrics.reporter.prom.class: org.apache.flink.metrics.prometheus.PrometheusReporter
              execution.checkpointing.interval: 10s
              execution.checkpointing.externalized-checkpoint-retention: RETAIN_ON_CANCELLATION

    ### Decrease the JobGraph translation thread pool size. This reduces our worst-case memory
    ### requirements by reducing the number of translations that can happen in parallel.
    ###
    ### See also: https://docs.ververica.com/platform_operations/advanced/sql.html
    sqlService:
      pool:
        coreSize: 1
        maxSize: 1

          
  blobStorageCredentials:
    existingSecret: minio-cred-secret-mirror

  ### Allow Ververica Platform to manage Apache Flink deployments in "vvp-jobs" namespace
  rbac:
    additionalNamespaces:
    - ververica-jobs

  ### Reduce gateway container memory requests.
  gateway:
    image:
      repository: ghcr.io/steadforce/applications/ververica-connector-gateway-steadforce
      tag: oracle-cdc
    resources:
      limits:
        memory: 1Gi
      requests:
        memory: 1Gi

  licenseConfigPath: file:/etc/vvp-licenses/license.yaml
  volumes:
    - name: license
      secret:
        secretName: ververica-license
  volumeMounts:
    - name: license
      mountPath: /etc/vvp-licenses/
