global:
  istio:
    ingressGateway:
      namespace: istio-ingress

subDomain: ververica

encryptedLicense: BABME9WYQRZ1WcJmJKADIrpZwxtOj657ejEsUyptdi2BtZJp6zQCjxEEAqafAZvmGxvPKMo+d+Z+lkSE+All5An4wgfa+00G9AINe7E/7FQtoHkNoKEfcXggpLdfm01PD65LGiH/Rul/RtUVwMEr5IbcQtGas+s79YTLXHrb7KLDQaEDGLu6hwNs1NMRuzGgVB3cAI+3GUO7+kiwHfYjnfYIQ5sZ+5fanAOp7sFXKWTIijf3W8WKzHUpK6QSKkqPBds/35RA9+bxUkHutvWkIZr/WzrZyur4SXl5XZjB2k8DGqHwIEOO6TLB95Q0p5uXcWVt5eNbpbXsaaD3ib59MJhAc+k/a25NYrn248k0aajBsJY+/ca6ehgsNAMvqEwUHOM0p04DSWxLZtZ6TGpTmGb5w2Eo3K1oY6o+qie1mf0b5uTPkr3+xvbpF/p+KO5Lhw8CuGvLydEetYbTVl1D0q1Wbr1/u8H3TVL//IW+GOL8BdSBzYs/W3BFfzXc/XXCENgFZNomY6djIrjIQybzcOmugQHPilZu8GX2jRlCGlu12zVakfHmGYGuvQL1JMevPhwNhCQRw3y+LU5uE9s4M3nsAM8DBZAcPc9d1JZlwXC8gfx3KiNCXv6teLnXV5PTFKt2bqqoYDqZ9hH3bXfc//nMRc+19b1RH0B6QGe23ZU1dM0TdcoXK7baSbKQnwryM2Aze290CkwcmIEtgoXr/TIE4P7aGREN5i3j2IjQycSpkQJDH89Qv69IlW0va+uTwfQJx6twnxOSf3KDpESFnJRMkNg0JT9ymh+ilnZo1+exYUWugcqJNiaHPjmkMiY/tGnCHUU1HXVtHwNsY0fcqsCAQHx+D/V/EFUYio5qJ90bSH1fa9MqnJ6l6VsdO5W+98fyvV8JWdzMlU7j1LFn1jLyKI/7SLlZFdYyjTvJRHu+mOjSwX/HF+Exzknrdg5bV+khbTMNBJFbCebEeJK/OSim5/jTmzcp8jXhIUgu71/7LF8BTjOjg+V0cul/ltQnua/HDBPoXOUgM4EgKz+7g3lWB5ol38c9Y1L1m2CDNAq0iGylJuY4ppruKCUlzUMPF+w8W53PQbU5+LSwtzk1NuMTmifPJHtCyIiZFWCNgEG9IoTc19u5QKSBnnwqaQOtbDOjK+9bgKaVQB++sCrI9/q7mTRnEXLM8Z6vMXrnVTePCZrhf9BUanVwv1xXsePfnkBVyJdFLUGFyV6hlaLx7dAxc0KPtpHEwgEEUPQLHq5HztGRyfDaiykCui9tbw6sifN81cVMAyZWQZrA1Y6cxZ4cpdxXG+ULktdjMzS556cebOUsPSXWdH4dnQ8CdyFlTEcb5sqHqd058TR9019laiuiB2+V3bLNqfXsIFQ7oMUakaEi4fbAqO1eLZiES7HV2hwulf2oFHY9CCOBXfQDEJ7u3M5WxIWLgoAGUO93edR97yICl65ipPQnoQ8in1cVV5hhJWfcJcBlUsEeREipwHtoJI9wuvaBfvIv8Vz+oh2Nw5aZQ4DC23prPaN4PAg2sZsu2zVmTZz0AIYlAcXaBtz91B6MRpQHS0tSlwJN96MMK/CVDp4x0+1SD1gpI5JCvR32ZO8keBLvMsrQEFYimDVj6/wJGPQlBBgid4YKa91Db3TLbROquMk/XeX2GcDdBRVOZ26AdFI4ZLJaC/QZwG51Sg8yGx64Gq9WJK5b9W2KM01V9V+0B0X7t8hniGyv+Lht0ncjBqD/LLnTgT2MP3tXl2LytQClZ5o0om4e76ky4nOivWQ/r6U6J4xEtqwh4iYraurNcFejbIXG7NbZE0wfQSoY4JwEGHt6wghozD6ZFwE0DsKUnqJn628WFBsSvYjgbwojHf66V8LQlByYAllomFOLYlsXB+kcPvhpoH2ZtE5SKMYK5C2bwMg8B51xgf8nWZ0K6e+WnetkV+y1Ql1FiaAl4rdWrzk/kvtQCzMrbh3S9nlh83iuO7Stivopm3ciz88dCtNi3MpyjejVLs0BeNOum0/Np6+slyiiNG8Otr/04H+yRMnZqGhQxvD9ZHy2C2uScU1ZPAGus3s9QPOeke7Q1s8hvNNUnU9gFPMvxg9FXrkhmm1MmVeHLTqxEyoQ5CPT167Ue1qlYnrvnivz6djgPubULiHjQnj919HTh/yJHLIJT06mBNid9Sm3OMSQiryhhmacy/X+Ov18vGFPwZaTt+SUbXRGuIgX18RVstMDL3EnTuMi/xAS7io7a0yzErjeD56OiyjN1q6nbezmdtRdIwNx1fcXRUl760hM+EsTDlKbolJrYAqdSPCJOLtonlDIQSfgrIll8Q4wLxHleWqamsPY0iVBK7/d/QQNL+RTr3H/H/HM7og9utbETLKWC+uQkwtH6MA59Fv52W5IiGkB99oaY8ag89Z5xUy1jFTXNrVsuY3gD2r0nDdbaKXGDPSKMcQO/2JxiglDlzZpYVju7Xi8UdYsVh+nBhQ26BjJgicRQhtDycA6N9J4KvnBDNGMSgzSrr6yw7EaOYRfUzks/J3FEwUGRO5T8gbxI7PU47WHUv601PvHHdQGDnvdqLCxgFpANACLZqb16gAjpxf/CoApkTicVMr2N2hebgkaLXwe2MZNxWQQ+QHKXZrIhGZwXiKWIVZgKmb+ZTK8FJBE8gEB7C7SKVY4fmQfOSX/gKZbnMeL6Xw44FTfPCuWUJJbGvlmOaQXGPtQIRKHh+43C7rV7NNFtuTgy9pyNMc00eFNV1v3mVYC6FNDOYVpvoXkNm6UfZbK3MrV9FsVWbKI2MotyhmhGk0alcpTR6KHz3ACYM+szSFpPV4LP4vInz+Ogh6IdVM5J0AwUWD+2CYIp5BeJ5KZ5N5Fy9PkOHNtY6LSoFjFi+UIIQoD6D2RB+U2ibt8ESC+hWzhZ56B3e4UFz2hhz5pXcwn5HJWZ5uCgYfzgl1PzIXaCOCRTbgI71b4navy0K98VXPehv2MyFp3i+ay+nbN/8TGlyHhB1/dRgS25HdV7MUW1j0r7fhlB7egBDCY7tj9gug7ssFpnZRkMMb5pkV7ijWLl66LVSTLlL9XJcO9dPm2PMrAHU8fSbPHm9rFjov7dLcvmZF/f3PAaKlxRBFyAW6nhY1i8kkhlmvWnOxGE9qIh8JR08Hy4mMXvlzk4t+DlHiXZgWl9C3lj8iKQyclodpGXHvUuRhkpxiLR+fILGGRZYymYipidqei2bih4i5b6oJ/BCmBVwKnC9XCs42f6IaOqthi8fSbmT23HYtP9/zIyY3IzNbTz3C3FLyqSJQwCRMiIcwcvoExul1SJxi9BGNBIYdKFsRrJJ//xjSnqarHbBUS14dPxoGdjiweFhN99y97mlIMuW/n2enFvenbR+x8mBUjjkD3+JxzkQwdPxMQ4XM+2MGi1zOUklPxlnqdNegGRekm3OKSF2ErkWmpB5gx6TNL7168JNK8ZJqTor7gZlf7ls5mhAl/l3nFGqFHoTS2iQ=

ververica-platform:
  vvp:
    ### Configure VVP to use a local SQLite database
    persistence:
      type: local

    ### Configure Minio for Universal Blob Storage
    blobStorage:
      baseUri: s3://steadops-playground-bucket
      s3:
        endpoint: http://minio.minio.svc.cluster.local:80

    ### Configure some global defaults for Deployments in this instance of Ververica Platform
    globalDeploymentDefaults: |
      spec:
        state: RUNNING
        template:
          spec:
            resources:
              jobmanager:
                cpu: 0.5
                memory: 1G
              taskmanager:
                cpu: 0.5
                memory: 1G
            flinkConfiguration:
              state.backend: filesystem
              taskmanager.memory.managed.fraction: 0.0 # no managed memory needed for filesystem statebackend
              high-availability: kubernetes
              metrics.reporter.prom.class: org.apache.flink.metrics.prometheus.PrometheusReporter
              execution.checkpointing.interval: 10s
              execution.checkpointing.externalized-checkpoint-retention: RETAIN_ON_CANCELLATION

    ### Decrease the JobGraph translation thread pool size. This reduces our worst-case memory
    ### requirements by reducing the number of translations that can happen in parallel.
    ###
    ### See also: https://docs.ververica.com/platform_operations/advanced/sql.html
    sqlService:
      pool:
        coreSize: 1
        maxSize: 1

          
  blobStorageCredentials:
    existingSecret: minio-cred-secret-mirror

  ### Allow Ververica Platform to manage Apache Flink deployments in "vvp-jobs" namespace
  rbac:
    additionalNamespaces:
    - ververica-jobs

  ### Reduce gateway container memory requests.
  gateway:
    resources:
      limits:
        memory: 1Gi
      requests:
        memory: 1Gi

  licenseConfigPath: file:/etc/vvp-licenses/license.yaml
  volumes:
    - name: license
      secret:
        secretName: ververica-license
  volumeMounts:
    - name: license
      mountPath: /etc/vvp-licenses/
