global:
  istio:
    ingressGateway:
      namespace: istio-ingress

subDomain: ververica

encryptedLicense: BACFrtjG9Q6UAa0TAR2SkgPSeAhcLx3wDUsyZLHfIDD+akVZX70yRuBGNhsUMVCuJmrnHB4fWvllQTDclOBdkZ3qeF3uLc58tN7ehaKDud/jB6R7T9ggA9ht9Ghe+Ywh9uP+ClIFlv5yQi7pWFZ43WwrOJg10RZZJZwZk8UvKrDumYfKAVygECGeSFJ3l03yoUOd7AUCUo86RrpQ84lwAig2y8YB8lpM/24GkiH70nR6BHcrKxgqRasvMaBqPNO+PSQQ0DUwsQtalurK5VDIZem4TRePe6idIZTa11ThcdjLcyW1rUk0HRMqvS3UXAfR7ETZPilBSYOPGAd0AemXGTViaLqXnixSKneXJx46SfKBBHQw/4EbxqeT6toX46+kpeFxN8A30bEA3nA6t8+9DAUrz1U5d00ROIrVRNn+G9Bwu9NPvMmegEa1tdWDwImL/VRfCNuLl9xd2Szl2scAs9GeSCxeo6zB5eB2Wa5W33y6ODDK18bQyr04CWwpBNac3Qw7I6BfsO9Yu40DnIxPKtO3s/E1HvPqmB6EmOUpecACiI4N9mbl5XK/JUzX4SiHPa5GnT9PNZvC8y5oPQ0Qzi7J/s6Ya5OniZfZ9pv6m3XCIfNVlbm7t0EIN6dBK0hP5Cvo//kw8RZ3URAHyKPxTvuC3EBoLW8eS4C73cqWyaqr/NJNfKwXQvsqH1EK1gJsKNK2iBaltMbupbsTiu7feAgbHSZV8PfCN7QyolPT3zVv+Q1fX4h2hZCy4CyaMhr881PEF9btgDpFv9Jd55obL6jLf7cLFvXVUxcds7/O06KLxu98FByhZXvtVqV+zHb1ARi/rYN0SitqCr08DP87Zeu5wQEAVREVODAWUV9npqe4l2KEIlC7kMV++SSWWK7FIUTHyg7kbsESazYrp2B/Ki1CpSA4r+4nX4/gvK0F8HYeHQIpoYc6oiWMbYa7NnienTdTFj+RIsU8Z2Wxo8IBUl6b9/Xurc8PjFjlTpxV4w2gRn+QUWlU3mp4mrFuqHTyfDma5SFXKtpv/66/fgUJnuIi7UCZMMcUdAGHfn/UL9hyl5pFQ7EmMm5s9AWtLHjvPETkm7bBWiob+x7R4e+UhvvXZufiul9g+abx3VuXmG9imepIsV4uFyBCmFAyxNABdJvHagUq2CMEu/od5X21+UODpE8nmr/e7awYZp9OGpTNmQeavHunbfp2tQfd8xkb2Jtq1MqZ11TmL6Qt2r3DGHNRF7vTcseGc1okd9cmihQqFlXDz9QlH/yuWy+/MhmMVs3mG/vJkdafSRS9HhQchxazHA8xfj3M4Nj5P+0fswEKAdlqQeRpuZmdYYwHK7bdJ+/sHoemXXpjqPn6fy4Vff72dXmt3fktS0bjSFvgMz9DrA==

ververica-platform:
  vvp:
    ### Configure VVP to use a local SQLite database
    persistence:
      type: local

    ### Configure Minio for Universal Blob Storage
    blobStorage:
      baseUri: s3://steadops-playground-bucket
      s3:
        endpoint: http://minio.minio.svc.cluster.local:80

    ### Configure some global defaults for Deployments in this instance of Ververica Platform
    globalDeploymentDefaults: |
      spec:
        state: RUNNING
        template:
          spec:
            resources:
              jobmanager:
                cpu: 0.5
                memory: 1G
              taskmanager:
                cpu: 0.5
                memory: 1G
            flinkConfiguration:
              state.backend: filesystem
              taskmanager.memory.managed.fraction: 0.0 # no managed memory needed for filesystem statebackend
              high-availability: kubernetes
              metrics.reporter.prom.class: org.apache.flink.metrics.prometheus.PrometheusReporter
              execution.checkpointing.interval: 10s
              execution.checkpointing.externalized-checkpoint-retention: RETAIN_ON_CANCELLATION

    ### Decrease the JobGraph translation thread pool size. This reduces our worst-case memory
    ### requirements by reducing the number of translations that can happen in parallel.
    ###
    ### See also: https://docs.ververica.com/platform_operations/advanced/sql.html
    sqlService:
      pool:
        coreSize: 1
        maxSize: 1

          
  blobStorageCredentials:
    existingSecret: minio-cred-secret-mirror

  ### Allow Ververica Platform to manage Apache Flink deployments in "vvp-jobs" namespace
  rbac:
    additionalNamespaces:
    - ververica-jobs

  ### Reduce gateway container memory requests.
  gateway:
    resources:
      limits:
        memory: 1Gi
      requests:
        memory: 1Gi

  licenseConfigPath: file:/etc/vvp-licenses/license.yaml
  volumes:
    - name: license
      secret:
        secretName: ververica-license
  volumeMounts:
    - name: license
      mountPath: /etc/vvp-licenses/
