kind: VvpDeployment
apiVersion: ververica.platform/v1
metadata:
  name: top-speed-windowing-example
  annotations:
    # ensure that we deploy this after ververica rollout
    argocd.argoproj.io/sync-wave: "5"
spec:
  syncingMode: PATCH
  deployment:
    userMetadata:
      name: top-speed-windowing-example
      namespace: default
    spec:
      deploymentTargetId: null
      deploymentTargetName: test
      maxJobCreationAttempts: 4
      maxSavepointCreationAttempts: 4
      restoreStrategy:
        allowNonRestoredState: false
        kind: LATEST_STATE
      sessionClusterName: null
      state: RUNNING
      template:
        metadata:
          annotations:
            flink.queryable-state.enabled: 'false'
            flink.security.ssl.enabled: 'false'
        spec:
          artifact:
            entryClass: org.apache.flink.streaming.examples.windowing.TopSpeedWindowing
            flinkImageRegistry: registry.ververica.com/v2.12
            flinkImageRepository: flink
            flinkImageTag: 1.17.2-stream1-scala_2.12-java11
            flinkVersion: '1.17'
            jarUri: >-
              https://repo1.maven.org/maven2/org/apache/flink/flink-examples-streaming_2.12/1.17.2/flink-examples-streaming_2.12-1.17.2-TopSpeedWindowing.jar
            kind: JAR
            mainArgs: '--windowSize 10 --windowUnit minutes'
          flinkConfiguration:
            execution.checkpointing.externalized-checkpoint-retention: RETAIN_ON_CANCELLATION
            execution.checkpointing.interval: 10s
            execution.checkpointing.min-pause: 10s
            high-availability: kubernetes
            metrics.reporter.prom.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory
            state.backend: filesystem
            taskmanager.memory.managed.fraction: '0.0'
            taskmanager.numberOfTaskSlots: '1'
            web.cancel.enable: 'false'
          logging:
            log4jLoggers:
              '': INFO
            loggingProfile: default
          parallelism: 1
          resources:
            jobmanager:
              cpu: 1
              memory: 1G
            taskmanager:
              cpu: 1
              memory: 2G
      upgradeStrategy:
        kind: STATEFUL
