apiVersion: v1
kind: Service
metadata:
  name: flink-metrics
  labels:
    system: ververica-platform
    app: flink-job
    component: metrics
spec:
  selector:
    system: ververica-platform
    app: flink-job
  ports:
    - name: metrics
      port: 9249
      targetPort: 9249
      protocol: TCP